name: "caiso_oasis"
description: "CAISO OASIS connector for DAM/FMM/RTM LMP, Ancillary Services, and CRR datasets via SingleZip API"
version: "1.0.0"

# Connector configuration
config:
  caiso_base_url: "${CAISO_OASIS_BASE_URL:https://oasis.caiso.com/oasisapi}"
  caiso_timeout: 60
  caiso_rate_limit: 50
  caiso_retry_attempts: 3
  caiso_backoff_factor: 2.0
  default_market_run_id: "DAM"
  default_node: "TH_NP15_GEN-APND"
  batch_size: 1000
  max_records: 5000
  oasis_version: "12"

market: "CAISO"
mode: "batch"
schedule: "0 */1 * * *"
enabled: true

# Raw output topics for different data types
output_topics:
  lmp_dam: "ingestion.market.caiso.lmp.dam.raw.v1"
  lmp_fmm: "ingestion.market.caiso.lmp.fmm.raw.v1"
  lmp_rtm: "ingestion.market.caiso.lmp.rtm.raw.v1"
  as_dam: "ingestion.market.caiso.as.dam.raw.v1"
  as_fmm: "ingestion.market.caiso.as.fmm.raw.v1"
  as_rtm: "ingestion.market.caiso.as.rtm.raw.v1"
  crr: "ingestion.market.caiso.crr.raw.v1"

schema: "../../../specs/events/market/ingestion.market.ticks.raw.v1.avsc"
retries: 3
backoff_seconds: 30
tenant_strategy: "single"

transforms:
  - name: sanitize_numeric
  - name: add_market_metadata

tags:
  - market-data
  - energy
  - lmp
  - ancillary-services
  - congestion-rights

# Supported data types
supported_data_types:
  - "lmp_dam"
  - "lmp_fmm"
  - "lmp_rtm"
  - "as_dam"
  - "as_fmm"
  - "as_rtm"
  - "crr"

# Schedule overrides per dataset
dataset_schedules:
  lmp_dam: "0 * * * *"          # Hourly DAM LMP
  lmp_fmm: "*/15 * * * *"       # 15-minute FMM LMP
  lmp_rtm: "*/5 * * * *"        # 5-minute RTM LMP
  as_dam: "0 * * * *"           # Hourly DAM AS
  as_fmm: "*/15 * * * *"        # 15-minute FMM AS
  as_rtm: "*/5 * * * *"         # 5-minute RTM AS
  crr: "0 4 * * *"              # Daily CRR data

# Dataset configurations
dataset_configs:
  lmp_dam:
    queryname: "PRC_LMP"
    market_run_id: "DAM"
    resultformat: "6"
    description: "Day-Ahead Market Locational Marginal Prices"
  lmp_fmm:
    queryname: "PRC_LMP"
    market_run_id: "FMM"
    resultformat: "6"
    description: "Fifteen-Minute Market Locational Marginal Prices"
  lmp_rtm:
    queryname: "PRC_LMP"
    market_run_id: "RTM"
    resultformat: "6"
    description: "Real-Time Market Locational Marginal Prices"
  as_dam:
    queryname: "PRC_AS"
    market_run_id: "DAM"
    resultformat: "6"
    description: "Day-Ahead Market Ancillary Services"
  as_fmm:
    queryname: "PRC_AS"
    market_run_id: "FMM"
    resultformat: "6"
    description: "Fifteen-Minute Market Ancillary Services"
  as_rtm:
    queryname: "PRC_AS"
    market_run_id: "RTM"
    resultformat: "6"
    description: "Real-Time Market Ancillary Services"
  crr:
    queryname: "PRC_CRR"
    resultformat: "6"
    description: "Congestion Revenue Rights"
