# Basic CAISO connector configuration
name: caiso
version: 1.0.0
market: CAISO
mode: batch
schedule: "0 */1 * * *"  # Every hour
enabled: true
output_topic: ingestion.caiso.raw.v1
schema: schemas/raw_caiso_trade.avsc
retries: 3
backoff_seconds: 30
tenant_strategy: single
transforms:
  - name: sanitize_numeric
  - name: standardize_timezone
owner: platform
description: "CAISO market data connector for real-time and historical trading data"
tags:
  - market-data
  - energy
  - trading
  - real-time

# CAISO-specific configuration
caiso_base_url: "https://oasis.caiso.com/oasisapi"
caiso_timeout: 30
caiso_rate_limit: 100
caiso_retry_attempts: 3
caiso_backoff_factor: 2.0
caiso_user_agent: "254Carbon/1.0"

# OASIS-specific parameters
oasis_version: "12"
oasis_result_format: "6"  # CSV in ZIP
default_market_run_id: "DAM"  # Day Ahead Market
default_node: "TH_SP15_GEN-APND"  # SP15 Generation

# Kafka configuration
kafka_bootstrap_servers: "localhost:9092"
schema_registry_url: "http://localhost:8081"