# Advanced CAISO Connector Configuration
# This configuration includes all available options for production use

name: caiso_advanced_example
version: 1.0.0
market: CAISO
mode: hybrid  # Supports both batch and real-time
schedule: "0 */1 * * *"  # Run every hour for batch, real-time runs continuously
enabled: true
output_topic: ingestion.caiso.raw.v1
schema: schemas/raw_caiso_trade.avsc
retries: 5
backoff_seconds: 60
tenant_strategy: multi  # Support multiple tenants
transforms:
  - sanitize_numeric
  - standardize_timezone
  - validate_required_fields
  - enrich_metadata
owner: platform
description: "Advanced CAISO connector with comprehensive configuration for production use"
tags:
  - market-data
  - energy
  - california
  - production
  - real-time

# Kafka settings
kafka_bootstrap_servers: "localhost:9092"
schema_registry_url: "http://localhost:8081"

# CAISO specific settings
caiso_api_key: null  # Not required for OASIS
caiso_base_url: "https://oasis.caiso.com/oasisapi"
caiso_timeout: 45
caiso_rate_limit: 200
caiso_retry_attempts: 5
caiso_backoff_factor: 2.5
caiso_user_agent: "254Carbon/1.0 (Production Environment)"

# OASIS API settings
oasis_version: "12"
oasis_result_format: "6"  # CSV in ZIP format
default_market_run_id: "DAM"

# Default nodes for different data types
default_node: "TH_SP15_GEN-APND"
backup_nodes:
  - "TH_NP15_GEN-APND"
  - "TH_SP15_GEN-APND"
  - "TH_ZP26_GEN-APND"

# Market run IDs to extract
market_run_ids:
  - "DAM"  # Day-Ahead Market
  - "RTM"  # Real-Time Market

# Time window settings for different modes
batch_window_hours: 24
real_time_window_minutes: 60
overlap_minutes: 5  # Overlap to avoid data gaps

# Data quality settings
quality_thresholds:
  completeness: 0.95
  accuracy: 0.90
  consistency: 0.95

# Performance tuning
performance:
  max_concurrent_requests: 3
  request_delay_seconds: 1.0
  memory_limit_mb: 1024
  timeout_multiplier: 1.5
